# Generated by Django 5.2.10 on 2026-01-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="money_type",
            field=models.CharField(
                choices=[("HAND CASH", "Hand_cash"), ("UPI CASH", "Upi_cash")],
                default=1130,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
