# Generated by Django 5.2.10 on 2026-01-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_transaction_money_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="money_type",
            field=models.CharField(
                choices=[("HAND CASH", "Hand Cash"), ("UPI CASH", "UPI Cash")],
                default="HAND CASH",
                max_length=20,
            ),
        ),
    ]
